from __future__ import annotations

import genanki

MODEL_ID = 1761198205290
MODEL_NAME = "saCloze++"
FRONT_TEMPLATE = "<div id=\"kard\">\n\n<div class=\"tbar\" data-seconds=\"12\" role=\"timer\" aria-label=\"Front timer\">\n  <div class=\"ttrack\"><div class=\"tfill\"></div></div>\n  <span class=\"tleft\">00:12</span>\n</div>\n\n<div class=\"tags\">{{Tags}}</div>\n{{edit:cloze:Text}}\n</div>\n\n<script>\n(function(){\n  function isIOSClient(){\n    var htmlCls = (document.documentElement && document.documentElement.className) || \"\";\n    var bodyCls = (document.body && document.body.className) || \"\";\n    var cls = (htmlCls + \" \" + bodyCls).toLowerCase();\n    return /\\biphone\\b|\\bipad\\b/.test(cls);\n  }\n\n  if (!isIOSClient()) return;\n\n  function colorFor(p){\n    var hStart = 170, hEnd = 0, h = hEnd + (hStart - hEnd) * p;\n    return \"hsl(\" + h + \",95%,55%)\";\n  }\n  function pad2(n){ return (n<10 ? \"0\" : \"\") + n; }\n\n  function startTimerOn(el){\n    if (!el || el.hasAttribute(\"data-bar-started\")) return;\n    el.setAttribute(\"data-bar-started\",\"1\");\n\n    var secs = parseFloat(el.getAttribute(\"data-seconds\") || \"12\");\n    if (!(secs > 0)) secs = 1;\n\n    var fill = el.querySelector(\".tfill\");\n    var txt = el.querySelector(\".tleft\");\n    if (!fill || !txt) return;\n\n    var durMs = secs * 1000;\n    var start = performance.now();\n\n    function tick(t){\n      var left = Math.max(0, durMs - (t - start));\n      var frac = left / durMs;\n\n      fill.style.width = (frac * 100).toFixed(3) + \"%\";\n      fill.style.background = colorFor(frac);\n\n      var s = Math.ceil(left / 1000);\n      var mm = Math.floor(s / 60);\n      var ss = s % 60;\n      txt.textContent = mm ? (mm + \":\" + pad2(ss)) : (s + \"s\");\n\n      if (left > 0) {\n        requestAnimationFrame(tick);\n      } else {\n        el.classList.add(\"done\");\n      }\n    }\n\n    requestAnimationFrame(tick);\n  }\n\n  function scanAndStart(){\n    var bars = document.querySelectorAll(\".tbar\");\n    for (var i = 0; i < bars.length; i++) startTimerOn(bars[i]);\n  }\n\n  scanAndStart();\n\n  var mo = new MutationObserver(function(){\n    scanAndStart();\n  });\n\n  if (document.body){\n    mo.observe(document.body, { childList: true, subtree: true });\n  } else {\n    document.addEventListener(\"DOMContentLoaded\", function(){\n      mo.observe(document.body, { childList: true, subtree: true });\n      scanAndStart();\n    });\n  }\n})();\n</script>\n\n<br>\n\n{{edit:tts en_US voices=Apple_Evan_(Enhanced) speed=1.1:cloze:Text}}\n"
BACK_TEMPLATE = "<div id=\"kard\">\n\n<div class=\"tbar\" data-seconds=\"12\" role=\"timer\" aria-label=\"Front timer\">\n  <div class=\"ttrack\"><div class=\"tfill\"></div></div>\n  <span class=\"tleft\">00:12</span>\n</div>\n\n<div class=\"tags\" id='tags'>{{Tags}}</div>\n{{edit:cloze:Text}}\n<div>&nbsp;</div>\n<div id='extra'>{{edit:Extra}}</div>\n\n</div>\n\n<script>\n(function(){\n  function isIOSClient(){\n    var htmlCls = (document.documentElement && document.documentElement.className) || \"\";\n    var bodyCls = (document.body && document.body.className) || \"\";\n    var cls = (htmlCls + \" \" + bodyCls).toLowerCase();\n    return /\\biphone\\b|\\bipad\\b/.test(cls);\n  }\n\n  if (!isIOSClient()) return;\n\n  function colorFor(p){\n    var hStart = 170, hEnd = 0, h = hEnd + (hStart - hEnd) * p;\n    return \"hsl(\" + h + \",95%,55%)\";\n  }\n\n  function pad2(n){ return (n<10 ? \"0\" : \"\") + n; }\n\n  function startTimerOn(el){\n    if (!el || el.hasAttribute(\"data-bar-started\")) return;\n    el.setAttribute(\"data-bar-started\",\"1\");\n\n    var secs = parseFloat(el.getAttribute(\"data-seconds\") || \"12\");\n    if (!(secs > 0)) secs = 1;\n\n    var fill = el.querySelector(\".tfill\");\n    var txt = el.querySelector(\".tleft\");\n    if (!fill || !txt) return;\n\n    var durMs = secs * 1000;\n    var start = performance.now();\n\n    function tick(t){\n      var left = Math.max(0, durMs - (t - start));\n      var frac = left / durMs;\n\n      fill.style.width = (frac * 100).toFixed(3) + \"%\";\n      fill.style.background = colorFor(frac);\n\n      var s = Math.ceil(left / 1000);\n      var mm = Math.floor(s / 60);\n      var ss = s % 60;\n      txt.textContent = mm ? (mm + \":\" + pad2(ss)) : (s + \"s\");\n\n      if (left > 0) {\n        requestAnimationFrame(tick);\n      } else {\n        el.classList.add(\"done\");\n      }\n    }\n\n    requestAnimationFrame(tick);\n  }\n\n  function scanAndStart(){\n    var bars = document.querySelectorAll(\".tbar\");\n    for (var i = 0; i < bars.length; i++) startTimerOn(bars[i]);\n  }\n\n  scanAndStart();\n\n  var mo = new MutationObserver(function(){\n    scanAndStart();\n  });\n\n  if (document.body){\n    mo.observe(document.body, { childList: true, subtree: true });\n  } else {\n    document.addEventListener(\"DOMContentLoaded\", function(){\n      mo.observe(document.body, { childList: true, subtree: true });\n      scanAndStart();\n    });\n  }\n})();\n</script>\n\n<br>\n\n{{edit:tts en_US voices=Apple_Evan_(Enhanced) speed=1.1:cloze-only:Text}}\n"
CSS = "html { overflow: scroll; overflow-x: hidden; }\n\n#kard {\npadding: 0px 0px;\nbackground-color:;\nmax-width: 700px;\nmargin: 0 auto;\nword-wrap: break-word;\nbackground-color: ;\n}\n\n.card {\nfont-family: helvetica;\nfont-size: 20px;\ntext-align: center;\ncolor: #D7DEE9;\nline-height: 1.6em;\nbackground-color: #2F2F31;\n}\n\n.cloze, .cloze b, .cloze u, .cloze i { font-weight: bold; color: MediumSeaGreen !important;}\n\n.tbar {\n  display: none;\n}\n\n.iphone .tbar,\n.ipad .tbar {\n  display: grid;\n}\n\n.tbar{\n  position: sticky; top: 0; z-index: 1;\n  grid-template-columns: minmax(0, 1fr) auto;\n  align-items: center;\n  column-gap: 8px;\n  padding: 6px 8px; margin: 0 0 12px 0;\n  background: rgba(16,24,40,.25); border: 1px solid rgba(34,50,77,.65);\n  border-radius: 12px; backdrop-filter: blur(6px);\n}\n.ttrack{\n  min-width: 0;\n  height: 8px; border-radius: 999px;\n  background: #102035; border: 1px solid #22324d; overflow: hidden;\n}\n.tfill{\n  height: 100%; width: 100%; background: #27d3ff;\n  transform-origin: left center;\n}\n.tleft{\n  display: inline-flex;\n  align-items: center;\n  font-size: 12px; color: #A6ABB9; line-height: 1;\n  white-space: nowrap; font-variant-numeric: tabular-nums;\n  min-width: 52px; text-align: right;\n}\n.tbar.done .tleft{ color:#CC5B5B }\n\n.tags{ pointer-events: none; }\n\n#extra, #extra i { font-size: 15px; color:#D7DEE9; font-style: italic; }\n\n#list { color: #A6ABB9; font-size: 10px; width: 100%; text-align: center; }\n\n.tags { color: #A6ABB9; opacity: 0; font-size: 10px; background-color: ; width: 100%; height: ; text-align: center; text-transform: uppercase; position: fixed; padding: 0px; top:0;  right: 0;}\n\nimg { display: block; max-width: 100%; max-height: none; margin-left: auto; margin: 10px auto 10px auto;}\nimg:active { width: 100%; }\ntr {font-size: 12px; }\n\nb { color: #C695C6 !important; }\nu { text-decoration: none; color: #5EB3B3;}\ni  { color: IndianRed; }\na { color: LightBlue !important; text-decoration: none; font-size: 14px; font-style: normal;  }\n\n::-webkit-scrollbar {\n    background: #fff;\n    width: 0px; }\n::-webkit-scrollbar-thumb { background: #bbb; }\n\n.mobile .card { color: #D7DEE9; background-color: #2F2F31; }\n.iphone .card img {max-width: 100%; max-height: none;}\n.mobile .card img:active { width: inherit; max-height: none;}\n"

MODEL = genanki.Model(
    MODEL_ID,
    MODEL_NAME,
    fields=[{"name": "Text"}, {"name": "Extra"}],
    templates=[{"name": "Cloze", "qfmt": FRONT_TEMPLATE, "afmt": BACK_TEMPLATE}],
    css=CSS,
    model_type=genanki.Model.CLOZE,
)

